### ISSUE TITLE
Filter a nullable property crash

### ISSUE THREAD

**Issue by ShaneGooseman** [timyhac/DevExtremeFilterBuilder#11]
When I filter for a nullable property I get an error.

var jsonFilter = @"[""ReutilizaAcometida"", ""="", true]";

ReutilizaAcometida acometida is nullable

**Comment by timyhac** [comment]
What kind of error? Runtime error? Compile-time error?

If you could provide a complete minimal example that would be great.

**Comment by ShaneGooseman** [comment]
Close, im filtering wrong.

**Comment by hkacem** [comment]
hi @ShaneGooseman , your filtering is working with nullables when your field "ReutilizaAcometida" is null on some elements of the collection?

I am facing the issue now, even with the Expression is correctly built, it fails on runtime.

Thanks.
