### ISSUE TITLE
Filtering error when filtering in collection.

### ISSUE THREAD

**Issue by ShaneGooseman** [timyhac/DevExtremeFilterBuilder#12]
`public class test
{
  public int Id { get; set; }
  public string? TestText { get; set; }
  public virtual ICollection<Test2>? Test2List { get; set; } = null;
}

public class test2
{
  public int Id { get; set; }
  public string? Test2Text { get; set; }
  public int TestId {get;set;}
  public virtual Test? Test { get; set; } = null;
}`

How can I filter in Test, by the properties of Test2?

if i apply the next filter

"[[\"Test2List.Id\",\"=\",1],\"and\",[\"Test2List.Test2Text\",\"startswith\",\"Hola\"]]"

i obtain the next error

"'Test2Text' is not a member of type System.Collections.Generic.ICollection`1[Test2]' (Parameter 'propertyOrFieldName')"

**Comment by timyhac** [comment]
I'm not really sure what you're trying to do but if you have an entity with a child entity as a property you should be able to refer to that property by name. For example:

```csharp
using DevExtremeFilterBuilder;

var query = """["Child.Text","startswith","T"]""";
var childTextStartsWithOne = new FilterBuilder().GetExpression<Parent>(query).Compile();

var data = new List<Parent>()
{
    new Parent(){ Child = new Child(){ Text = "One" } },
    new Parent(){ Child = new Child(){ Text = "Two" } },
    new Parent(){ Child = new Child(){ Text = "Three" } },
};

var filteredData = data.Where(childTextStartsWithOne);  // Two and Three

public class Parent
{
    public int Id { get; set; }
    public Child? Child { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string? Text { get; set; }
}
```

You might get some more info from the test solution: https://github.com/timyhac/DevExtremeFilterBuilder/blob/main/src/FilterBuilder.Tests/ConditionExpressionTests.cs#L100

**Comment by ShaneGooseman** [comment]
Yes, but I get an error if the child property is a list or an icollection

**Comment by timyhac** [comment]
Can you share a complete example, something that I can copy and paste and create a unit test for.

**Comment by ShaneGooseman** [comment]
The problem is that I am trying to filter a list by the property of a list item and I don't know how to do it.

As I show you in the first post. I try to filter by a property of Test2, when in Test1, what I have is a list of Test2.

**Comment by timyhac** [comment]
I'm so sorry, I still do not understand what you mean.

Assuming the relationship is something like this:

```csharp
class Parent
{
    public int Id { get; set; }
    public List<Child> Children { get; set; }
}

class Child
{
    public int Id { get; set; }
    public string Text { get; set; }
}
```

These are some guesses at what behaviour you're trying to achieve:
1. From a list of `parents`, get all of the `children` that have text starting with "Hola".
2. Find all of the `parents` that have any `children` whose text start with "Hola".
3. Find all of the `parents` that have have at least two `children`, and the second `child` has text starting with "Hola".

There was a way to add your own custom operators so you should be able to do any of these with that behaviour. I have some information on that in the README file here: https://github.com/timyhac/DevExtremeFilterBuilder#register-a-custom-condition-operator

Perhaps another way of explaining what you're trying to do is if you were to write the filter as a SQL query?

**Comment by ShaneGooseman** [comment]
The second option
"Find all of the parents that have any children whose text start with "Hola"."

**Comment by timyhac** [comment]
It has been a long time since I've used FilterBuilder but I don't recall it having the ability to filter with two different types.

But assuming you solve that problem and are able to mix types, I'd be looking to produce a specification object something like this: `["Children","atLeastOne",["Text", "startswith", "Hola"]]`

This would mean give me all Parents, where there is AtLeastOne Child whose Text startswith Hola.

To make this work however, you will at the very least need to add a custom operator to the FilterBuilder for `atLeastOne`, but frankly I'm not sure this will work in the current state of this component - I think there will be issues mixing the types.

I'm happy to take pull requests if you find a way to make this work.
