### ISSUE TITLE
How to make it not case sensitive?

### ISSUE THREAD

**Issue by ShaneGooseman** [timyhac/DevExtremeFilterBuilder#13]
String operations are case sensitive in .NET Core and in the FilterBuilder as well.

How can these methods be modified to be case sensitive?

`var stringContainsMethodInfo = typeof(string).GetMethod("Contains", new[] { typeof(string) });
            var stringStartsWithMethodInfo = typeof(string).GetMethod("StartsWith", new[] { typeof(string) });
            var stringEndsWithMethodInfo = typeof(string).GetMethod("EndsWith", new[] { typeof(string) });`

**Comment by timyhac** [comment]
What have you tried?

Seems like the .NET documentation has some guidance on how to call the Contains method with various StringComparison options: https://learn.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-7.0#system-string-contains(system-char-system-stringcomparison)

**Comment by ShaneGooseman** [comment]
Thank you!
I resolve it!
